### PR TITLE
[keepalive-tool] Keepalive wrapper utility

### PR DESCRIPTION
**Pull request by thp**
Allows wrapping a command call with CPU keepalive.

### CODE REVIEW

**Comment by thp** [comment]
Updated PR:

 * Commented out line in `Makefile` removed
 * Added `GOptionContext`-based command line parsing
 * Updated copyright line/contact info in header comment
 * Add `--timeout`/`-t` option to disable keepalive after a given number of seconds (doesn't kill child process, just disables keepalive)

**Comment by thp** [comment]
Storing the source ID in `timeout_source_id` now and cancelling it in `keepalive_free`.

**Comment by kjokinie** [comment]
I'm happy with merging this. If there's a problem with getting suspended before keepalive starts, it's not the end of the world, and we can fix it later. Code looks cleaner as it is now.

**Comment by spiiroin** [comment]
LGTM

**Pull request merged**
